ALTER TABLE "CashClosure"
ADD COLUMN "pendingMoney" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN "pendingMessengerPay" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN "internalSale" DECIMAL(12,2) NOT NULL DEFAULT 0,
ADD COLUMN "generalSale" DECIMAL(12,2) NOT NULL DEFAULT 0;
